### ISSUE TITLE
Add sensor metadata to observation reports

### ISSUE THREAD

**Issue by glencornell** [christianrowlands/network-survey-messaging#5]
Some sensors have directional antennae, which help in locating the position of transmitters.  This change request is intended to incorporate crude metadata about the status of the sensor: far clipping plane, field of view in degrees, and sensor orientation.  These are expected to be non-breaking optional new fields to ensure backwards compatibility with version 0.8.0 of this protocol.  These fields are proposed to be added to all of the topics.

I'll be happy to make the change and submit the pull request, should you accept the proposal.

**Comment by christianrowlands** [comment]
I am nervous about bloating this protocol/schema with too much information. I honestly am still not sure if the device status message really belonged in this messaging protocol, but I needed some basic information, similar to what you are looking for. I think we should discuss this further and flush it out a bit. Thanks for the proposal.

**Comment by glencornell** [comment]
I originally conceived this as a static description of the sensor characteristics.  In some cases, however, like a camera, one can change the viewing frustum (field of view, near/far clipping planes) dynamically.  And although this is a rudimentary description of an antenna, it could be used to locate the transmitter's location based upon fewer observations.
