### ISSUE TITLE
Change Proposal: add new message: wifi probe request message

### ISSUE THREAD

**Issue by glencornell** [christianrowlands/network-survey-messaging#7]
802.11 probe requests are particularly interesting in mapping applications.  This change request proposes a new message that captures probe requests (specifically Source Address and SSID).

If approved, I'll submit the pull request

**Comment by christianrowlands** [comment]
This makes sense and should be straightforward to add. It aligns with the rest of the messages well so I don't foresee any problems. Thanks for the proposal.

**Comment by christianrowlands** [comment]
I created a PR for this feature:  https://github.com/christianrowlands/network-survey-messaging/pull/9
