### ISSUE TITLE
Proposal: add a media observation record

### ISSUE THREAD

**Issue by glencornell** [christianrowlands/network-survey-messaging#8]
In some cases, it is useful to publish the location of media (Kismet DB, pcap files, etc) that are available to be ingested in the system but are too large to be efficiently transported through the existing transport mechanism (MQTT, gRPC, etc).  In this proposed use-case, the remote sensor will upload the media to a network location an then publish this media_observation_report topic for listeners to obtain and process asynchronously.

If approved, I'll submit the pull request.

**Comment by christianrowlands** [comment]
I need to think about this one a bit. My knee jerk reaction is that there are other protocols that are better suited to meet this requirement, and it falls outside the scope of this protocol schema. However, I need to think some more on what the user experience would be.

**Comment by christianrowlands** [comment]
I feel that the media observation record use case is outside the scope of this messaging api. I appreciate the suggestion, but I am closing this issue.
